INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (1, 'Bệnh viện Lê - Trương', 2668, 4634, 1);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (2, 'Khu cách ly Ngô and Sons', 133, 375, 2);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (3, 'Bệnh viện Nguyễn Group', 3074, 4264, 3);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (4, 'Khu cách ly Hà - Phùng', 3383, 2184, 4);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (5, 'Bệnh viện Đào Group', 1030, 2050, 5);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (6, 'Khu cách ly Ngô Inc', 33, 2117, 6);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (7, 'Bệnh viện Hoàng LLC', 1532, 101, 7);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (8, 'Khu cách ly Vương - Trịnh', 3454, 1806, 8);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (9, 'Bệnh viện Ngô, Trần and Lâm', 631, 1736, 9);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (10, 'Khu cách ly Đỗ - Đỗ', 4969, 1424, 10);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (11, 'Bệnh viện Hoàng Inc', 3958, 3834, 11);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (12, 'Khu cách ly Đỗ, Lâm and Trương', 4221, 986, 12);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (13, 'Bệnh viện Đinh, Mai and Vũ', 1622, 1914, 13);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (14, 'Khu cách ly Trần - Nguyễn', 4293, 416, 14);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (15, 'Bệnh viện Đinh - Lý', 2611, 4906, 15);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (16, 'Khu cách ly Hà, Đoàn and Dương', 1075, 3967, 16);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (17, 'Bệnh viện Phạm LLC', 1856, 4883, 17);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (18, 'Khu cách ly Nguyễn Inc', 4115, 3754, 18);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (19, 'Bệnh viện Phùng, Tô and Phan', 2776, 2592, 19);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (20, 'Khu cách ly Phùng, Trần and Phùng', 3617, 1713, 20);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (21, 'Bệnh viện Lê - Trương', 2023, 4567, 21);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (22, 'Khu cách ly Lý, Phạm and Đào', 2114, 3875, 22);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (23, 'Bệnh viện Mai LLC', 3483, 4383, 23);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (24, 'Khu cách ly Phạm - Bùi', 4492, 3682, 24);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (25, 'Bệnh viện Dương, Phan and Đoàn', 4424, 1269, 25);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (26, 'Khu cách ly Bùi - Tô', 909, 122, 26);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (27, 'Bệnh viện Đỗ, Nguyễn and Hồ', 893, 4691, 27);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (28, 'Khu cách ly Nguyễn, Phạm and Lý', 834, 1310, 28);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (29, 'Bệnh viện Vương - Ngô', 571, 4242, 29);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (30, 'Khu cách ly Đào - Lê', 2478, 3423, 30);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (31, 'Bệnh viện Đào Group', 798, 3312, 31);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (32, 'Khu cách ly Đoàn LLC', 2558, 1870, 32);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (33, 'Bệnh viện Hà - Vũ', 925, 73, 33);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (34, 'Khu cách ly Đỗ and Sons', 1708, 2582, 34);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (35, 'Bệnh viện Dương Group', 227, 3582, 35);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (36, 'Khu cách ly Đặng - Hồ', 1511, 551, 36);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (37, 'Bệnh viện Đỗ - Trương', 912, 1660, 37);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (38, 'Khu cách ly Lý, Đinh and Hà', 4657, 1427, 38);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (39, 'Bệnh viện Hồ Inc', 987, 1201, 39);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (40, 'Khu cách ly Hồ - Phan', 4749, 1710, 40);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (41, 'Bệnh viện Đặng Inc', 4525, 2275, 41);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (42, 'Khu cách ly Phạm, Vũ and Lâm', 1489, 4703, 42);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (43, 'Bệnh viện Hà - Vương', 1243, 771, 43);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (44, 'Khu cách ly Hoàng - Vương', 3453, 417, 44);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (45, 'Bệnh viện Vũ LLC', 805, 2841, 45);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (46, 'Khu cách ly Phan - Mai', 3200, 123, 46);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (47, 'Bệnh viện Trương - Đặng', 3565, 1783, 47);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (48, 'Khu cách ly Phùng, Tăng and Đỗ', 1439, 437, 48);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (49, 'Bệnh viện Phan Group', 2201, 4981, 49);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (50, 'Khu cách ly Lâm, Vương and Tô', 1529, 1540, 50);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (51, 'Bệnh viện Trần Group', 1527, 1029, 51);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (52, 'Khu cách ly Lâm Inc', 4204, 1354, 52);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (53, 'Bệnh viện Phạm Group', 2046, 2655, 53);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (54, 'Khu cách ly Tô - Trịnh', 4522, 2479, 54);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (55, 'Bệnh viện Ngô, Đặng and Vũ', 3759, 1051, 55);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (56, 'Khu cách ly Nguyễn Inc', 1901, 1082, 56);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (57, 'Bệnh viện Dương, Phạm and Đặng', 2452, 3810, 57);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (58, 'Khu cách ly Lê - Đào', 1980, 2141, 58);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (59, 'Bệnh viện Tăng, Phùng and Đoàn', 252, 347, 59);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (60, 'Khu cách ly Phan - Phùng', 2198, 4269, 60);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (61, 'Bệnh viện Trần, Đoàn and Hà', 2337, 4097, 61);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (62, 'Khu cách ly Trịnh, Nguyễn and Phạm', 4875, 242, 62);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (63, 'Bệnh viện Đỗ Inc', 2808, 1952, 63);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (64, 'Khu cách ly Nguyễn, Lâm and Đặng', 973, 720, 64);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (65, 'Bệnh viện Đoàn, Trịnh and Mai', 584, 4583, 65);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (66, 'Khu cách ly Phan, Đoàn and Vũ', 1437, 2682, 66);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (67, 'Bệnh viện Hà, Trịnh and Đặng', 2031, 621, 67);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (68, 'Khu cách ly Trương, Ngô and Đinh', 253, 3427, 68);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (69, 'Bệnh viện Lý - Đào', 3100, 3666, 69);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (70, 'Khu cách ly Nguyễn Group', 2841, 387, 70);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (71, 'Bệnh viện Trần - Lâm', 1135, 1280, 71);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (72, 'Khu cách ly Đoàn - Trịnh', 1089, 1023, 72);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (73, 'Bệnh viện Hồ Group', 1529, 580, 73);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (74, 'Khu cách ly Phùng - Đào', 617, 2745, 74);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (75, 'Bệnh viện Đỗ - Bùi', 3195, 3080, 75);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (76, 'Khu cách ly Đỗ Group', 3383, 2270, 76);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (77, 'Bệnh viện Đinh LLC', 1617, 1744, 77);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (78, 'Khu cách ly Phạm and Sons', 374, 4658, 78);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (79, 'Bệnh viện Hà - Phan', 2743, 710, 79);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (80, 'Khu cách ly Đào, Lâm and Tăng', 277, 3569, 80);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (81, 'Bệnh viện Trần Group', 2368, 3987, 81);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (82, 'Khu cách ly Hoàng and Sons', 3043, 1820, 82);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (83, 'Bệnh viện Dương - Tăng', 924, 4592, 83);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (84, 'Khu cách ly Hà LLC', 3945, 3004, 84);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (85, 'Bệnh viện Đoàn, Vương and Phùng', 3307, 1930, 85);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (86, 'Khu cách ly Lâm, Lý and Vương', 1889, 1340, 86);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (87, 'Bệnh viện Lâm - Trương', 1859, 1125, 87);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (88, 'Khu cách ly Hồ, Trần and Hoàng', 1987, 3586, 88);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (89, 'Bệnh viện Bùi - Hà', 2221, 2541, 89);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (90, 'Khu cách ly Trương and Sons', 4271, 2104, 90);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (91, 'Bệnh viện Đinh, Lê and Đào', 2613, 3313, 91);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (92, 'Khu cách ly Lâm Group', 4815, 4337, 92);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (93, 'Bệnh viện Hoàng, Đặng and Phan', 4822, 1270, 93);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (94, 'Khu cách ly Đặng, Đinh and Mai', 2454, 3547, 94);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (95, 'Bệnh viện Phùng - Dương', 3470, 321, 95);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (96, 'Khu cách ly Lê - Đào', 2691, 4171, 96);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (97, 'Bệnh viện Lê - Dương', 1701, 2214, 97);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (98, 'Khu cách ly Đỗ - Hồ', 1081, 3641, 98);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (99, 'Bệnh viện Đinh - Tăng', 4379, 1113, 99);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (100, 'Khu cách ly Lâm - Đỗ', 3260, 554, 100);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (101, 'Bệnh viện Lê, Mai and Dương', 1851, 4550, 101);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (102, 'Khu cách ly Nguyễn Group', 1054, 2082, 102);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (103, 'Bệnh viện Tô, Vương and Vương', 1686, 1701, 103);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (104, 'Khu cách ly Bùi, Lâm and Lâm', 3139, 2, 104);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (109, 'Bệnh viện Vương and Sons', 4970, 4889, 109);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (110, 'Khu cách ly Mai, Ngô and Hồ', 4085, 1124, 110);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (111, 'Bệnh viện Đỗ and Sons', 2443, 2793, 111);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (112, 'Khu cách ly Ngô - Lâm', 888, 1698, 112);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (108, 'Khu cách ly Vũ, Phan and Lê', 2448, 1875, 108);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (113, 'Bệnh viện Phan - Trương', 4100, 364, 113);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (115, 'Bệnh viện Dương - Lý', 4307, 2564, 115);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (118, 'Khu cách ly Hà - Bùi', 3633, 3786, 118);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (120, 'Khu cách ly Đào and Sons', 2825, 4008, 120);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (123, 'Bệnh viện Phan and Sons', 1025, 4308, 123);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (125, 'Bệnh viện Tô - Tăng', 3364, 628, 125);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (126, 'Khu cách ly Trịnh, Đoàn and Tăng', 3598, 1559, 126);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (130, 'Khu cách ly Lâm, Lâm and Tô', 539, 2048, 130);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (131, 'Bệnh viện Đặng - Hà', 4672, 835, 131);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (135, 'Bệnh viện Dương - Tăng', 3324, 1345, 135);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (136, 'Khu cách ly Đỗ, Hà and Phùng', 4429, 1514, 136);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (140, 'Khu cách ly Ngô Group', 4050, 2106, 140);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (141, 'Bệnh viện Mai - Phùng', 1296, 3689, 141);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (145, 'Bệnh viện Nguyễn and Sons', 995, 158, 145);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (146, 'Khu cách ly Hà - Hồ', 1986, 4500, 146);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (150, 'Khu cách ly Đào LLC', 3507, 1598, 150);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (151, 'Bệnh viện Trương LLC', 570, 1443, 151);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (155, 'Bệnh viện Phùng LLC', 4262, 4125, 155);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (156, 'Khu cách ly Tô Group', 933, 2816, 156);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (160, 'Khu cách ly Phùng, Phạm and Tô', 4242, 4510, 160);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (161, 'Bệnh viện Đào, Tăng and Tô', 250, 1930, 161);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (165, 'Bệnh viện Mai, Bùi and Dương', 3718, 4985, 165);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (167, 'Bệnh viện Đinh - Đỗ', 2460, 575, 167);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (171, 'Bệnh viện Đoàn and Sons', 2921, 4135, 171);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (172, 'Khu cách ly Đinh - Trương', 2964, 4466, 172);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (176, 'Khu cách ly Nguyễn, Phạm and Đoàn', 408, 1325, 176);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (177, 'Bệnh viện Vũ, Tăng and Dương', 818, 2244, 177);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (181, 'Bệnh viện Hồ, Hà and Trần', 3058, 3894, 181);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (182, 'Khu cách ly Hoàng and Sons', 1163, 2714, 182);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (186, 'Khu cách ly Đinh Group', 828, 2835, 186);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (187, 'Bệnh viện Vương Inc', 1770, 53, 187);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (191, 'Bệnh viện Bùi Inc', 3365, 940, 191);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (192, 'Khu cách ly Trịnh - Đinh', 2781, 1506, 192);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (196, 'Khu cách ly Phạm, Mai and Hoàng', 748, 455, 196);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (197, 'Bệnh viện Lý Inc', 1794, 3557, 197);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (201, 'Bệnh viện Phan, Mai and Đoàn', 4006, 22, 201);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (202, 'Khu cách ly Lý Group', 4019, 2162, 202);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (206, 'Khu cách ly Ngô - Nguyễn', 3060, 4922, 206);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (207, 'Bệnh viện Ngô Group', 138, 4332, 207);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (211, 'Bệnh viện Dương LLC', 4334, 2097, 211);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (212, 'Khu cách ly Đỗ, Trần and Hoàng', 4240, 2706, 212);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (216, 'Khu cách ly Bùi Inc', 3507, 574, 216);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (217, 'Bệnh viện Trương LLC', 285, 1991, 217);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (218, 'Khu cách ly Phùng, Trương and Hồ', 2113, 2299, 218);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (222, 'Khu cách ly Lý and Sons', 1417, 4274, 222);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (223, 'Bệnh viện Tăng, Trịnh and Tô', 428, 3897, 223);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (228, 'Khu cách ly Đỗ, Đỗ and Trịnh', 1575, 4487, 228);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (229, 'Bệnh viện Trần, Hoàng and Đinh', 3462, 3661, 229);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (231, 'Bệnh viện Đặng - Phan', 1804, 3073, 231);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (234, 'Khu cách ly Lê, Bùi and Nguyễn', 4536, 2677, 234);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (236, 'Khu cách ly Vũ, Hoàng and Tăng', 2261, 598, 236);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (238, 'Khu cách ly Hà, Tô and Lâm', 3693, 726, 238);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (241, 'Bệnh viện Lê, Lê and Trương', 3817, 2925, 241);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (243, 'Bệnh viện Đặng Group', 313, 3299, 243);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (246, 'Khu cách ly Tô, Hà and Đặng', 3210, 738, 246);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (248, 'Khu cách ly Phùng - Mai', 2309, 2480, 248);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (251, 'Bệnh viện Trương - Trần', 2549, 4247, 251);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (253, 'Bệnh viện Lâm Group', 1388, 3792, 253);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (254, 'Khu cách ly Hồ - Hồ', 4906, 1854, 254);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (258, 'Khu cách ly Phùng - Vương', 1131, 2665, 258);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (259, 'Bệnh viện Trần - Lê', 1145, 2178, 259);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (263, 'Bệnh viện Lê - Tô', 3647, 1715, 263);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (264, 'Khu cách ly Phùng LLC', 2062, 51, 264);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (268, 'Khu cách ly Hoàng, Lê and Trần', 3943, 392, 268);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (269, 'Bệnh viện Vương - Hà', 1838, 2454, 269);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (273, 'Bệnh viện Hồ, Mai and Vũ', 1169, 980, 273);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (274, 'Khu cách ly Ngô - Vương', 741, 1127, 274);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (278, 'Khu cách ly Nguyễn and Sons', 3725, 2898, 278);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (279, 'Bệnh viện Mai LLC', 1502, 3055, 279);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (282, 'Khu cách ly Phạm Inc', 999, 4930, 282);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (284, 'Khu cách ly Trương - Bùi', 256, 1450, 284);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (286, 'Khu cách ly Mai - Trịnh', 1888, 2758, 286);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (289, 'Bệnh viện Vương, Nguyễn and Đỗ', 1347, 4924, 289);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (291, 'Bệnh viện Dương LLC', 3150, 841, 291);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (295, 'Bệnh viện Lê Group', 4501, 2185, 295);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (297, 'Bệnh viện Đỗ Inc', 3364, 4020, 297);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (300, 'Khu cách ly Hoàng - Đỗ', 80, 1751, 300);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (302, 'Khu cách ly Hoàng - Tăng', 3868, 3201, 302);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (305, 'Bệnh viện Vũ and Sons', 3362, 1451, 305);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (307, 'Bệnh viện Trịnh, Nguyễn and Hồ', 97, 2628, 307);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (310, 'Khu cách ly Lê Inc', 2078, 1331, 310);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (312, 'Khu cách ly Đặng Inc', 4557, 3228, 312);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (315, 'Bệnh viện Mai - Đặng', 93, 265, 315);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (317, 'Bệnh viện Mai and Sons', 1718, 4577, 317);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (320, 'Khu cách ly Đoàn, Đinh and Phan', 2027, 3366, 320);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (322, 'Khu cách ly Đỗ LLC', 20, 1036, 322);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (325, 'Bệnh viện Đoàn and Sons', 385, 1350, 325);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (327, 'Bệnh viện Trịnh, Trần and Lý', 663, 1170, 327);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (330, 'Khu cách ly Đào, Bùi and Phan', 3579, 2770, 330);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (332, 'Khu cách ly Trương - Phùng', 299, 4786, 332);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (335, 'Bệnh viện Phạm - Hà', 673, 593, 335);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (337, 'Bệnh viện Ngô LLC', 1368, 1795, 337);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (340, 'Khu cách ly Tô - Bùi', 135, 271, 340);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (342, 'Khu cách ly Lê - Nguyễn', 748, 2575, 342);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (345, 'Bệnh viện Trương, Mai and Phan', 4217, 2542, 345);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (346, 'Khu cách ly Phùng, Phan and Mai', 777, 3865, 346);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (350, 'Khu cách ly Hồ, Vương and Hồ', 1084, 940, 350);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (351, 'Bệnh viện Mai Group', 12, 4426, 351);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (355, 'Bệnh viện Phạm - Hoàng', 14, 3797, 355);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (356, 'Khu cách ly Ngô and Sons', 3816, 1026, 356);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (360, 'Khu cách ly Nguyễn - Lâm', 4628, 4253, 360);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (106, 'Khu cách ly Đỗ - Đỗ', 1617, 2141, 106);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (114, 'Khu cách ly Hà, Hà and Phạm', 3582, 2818, 114);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (119, 'Bệnh viện Trần - Mai', 1935, 1783, 119);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (124, 'Khu cách ly Phùng, Nguyễn and Nguyễn', 2479, 1544, 124);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (129, 'Bệnh viện Tăng - Vương', 3290, 1166, 129);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (134, 'Khu cách ly Trương Inc', 727, 3412, 134);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (139, 'Bệnh viện Bùi Inc', 4113, 1773, 139);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (144, 'Khu cách ly Nguyễn and Sons', 232, 1151, 144);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (149, 'Bệnh viện Trương - Vũ', 4287, 396, 149);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (154, 'Khu cách ly Đoàn, Đỗ and Đặng', 3771, 3448, 154);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (159, 'Bệnh viện Phạm - Đinh', 4578, 4178, 159);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (164, 'Khu cách ly Vũ, Trương and Dương', 832, 4935, 164);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (166, 'Khu cách ly Đinh, Tăng and Bùi', 1657, 2517, 166);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (170, 'Khu cách ly Đặng, Nguyễn and Vũ', 1644, 4157, 170);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (175, 'Bệnh viện Hồ and Sons', 3938, 3511, 175);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (180, 'Khu cách ly Tăng LLC', 4365, 118, 180);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (185, 'Bệnh viện Hoàng, Hồ and Đào', 559, 329, 185);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (190, 'Khu cách ly Hồ - Tô', 4106, 4724, 190);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (195, 'Bệnh viện Mai, Hà and Hồ', 4300, 4701, 195);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (200, 'Khu cách ly Vũ, Trịnh and Đinh', 1358, 4286, 200);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (205, 'Bệnh viện Lý, Vũ and Phan', 1442, 230, 205);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (210, 'Khu cách ly Đặng and Sons', 4938, 1525, 210);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (215, 'Bệnh viện Hồ - Nguyễn', 3332, 623, 215);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (221, 'Bệnh viện Phùng Group', 3, 2564, 221);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (227, 'Bệnh viện Tô, Đinh and Đoàn', 1328, 4558, 227);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (233, 'Bệnh viện Ngô - Lê', 1823, 593, 233);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (239, 'Bệnh viện Trương, Hồ and Tăng', 3049, 517, 239);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (244, 'Khu cách ly Tăng and Sons', 1092, 3399, 244);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (249, 'Bệnh viện Đào - Trịnh', 2599, 1374, 249);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (255, 'Bệnh viện Tăng - Mai', 3999, 4528, 255);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (260, 'Khu cách ly Lâm Inc', 982, 2045, 260);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (265, 'Bệnh viện Trần Group', 885, 78, 265);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (270, 'Khu cách ly Lý Inc', 4915, 4353, 270);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (275, 'Bệnh viện Lý Inc', 227, 3122, 275);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (280, 'Khu cách ly Lý and Sons', 3425, 1813, 280);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (285, 'Bệnh viện Đặng, Lê and Đặng', 4793, 3067, 285);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (290, 'Khu cách ly Lâm Inc', 4826, 3739, 290);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (296, 'Khu cách ly Phùng - Hồ', 1593, 4709, 296);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (301, 'Bệnh viện Đinh - Lâm', 4013, 353, 301);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (306, 'Khu cách ly Đặng, Trần and Vũ', 795, 4439, 306);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (311, 'Bệnh viện Phạm - Tăng', 181, 1136, 311);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (316, 'Khu cách ly Đỗ - Đào', 0, 2542, 316);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (321, 'Bệnh viện Hồ - Ngô', 1339, 285, 321);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (326, 'Khu cách ly Phan and Sons', 1291, 4302, 326);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (331, 'Bệnh viện Đoàn, Mai and Hồ', 2624, 4567, 331);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (336, 'Khu cách ly Lý LLC', 642, 844, 336);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (341, 'Bệnh viện Phùng, Ngô and Ngô', 2976, 2028, 341);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (347, 'Bệnh viện Đỗ - Bùi', 511, 2410, 347);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (352, 'Khu cách ly Đoàn and Sons', 2149, 4413, 352);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (357, 'Bệnh viện Tăng, Trương and Dương', 4070, 2283, 357);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (362, 'Khu cách ly Dương, Nguyễn and Phùng', 1907, 3056, 362);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (367, 'Bệnh viện Phạm Inc', 1758, 2442, 367);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (372, 'Khu cách ly Đặng, Lý and Đinh', 4243, 4415, 372);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (377, 'Bệnh viện Trương Inc', 3964, 4296, 377);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (382, 'Khu cách ly Hà Inc', 637, 2333, 382);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (387, 'Bệnh viện Lê - Trần', 1982, 2295, 387);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (392, 'Khu cách ly Đoàn - Lý', 3234, 1826, 392);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (397, 'Bệnh viện Tô, Vương and Lý', 4060, 4053, 397);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (402, 'Khu cách ly Trịnh - Đặng', 3426, 3347, 402);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (408, 'Khu cách ly Trần - Hà', 3458, 261, 408);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (413, 'Bệnh viện Đào and Sons', 32, 893, 413);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (418, 'Khu cách ly Vương, Vũ and Dương', 860, 4446, 418);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (423, 'Bệnh viện Tô, Đặng and Tăng', 239, 3416, 423);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (428, 'Khu cách ly Lê LLC', 1111, 3233, 428);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (433, 'Bệnh viện Trần, Tô and Hồ', 4254, 3602, 433);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (438, 'Khu cách ly Nguyễn, Trịnh and Vương', 1860, 3516, 438);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (443, 'Bệnh viện Đào - Đào', 4127, 2334, 443);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (448, 'Khu cách ly Phạm and Sons', 3416, 1780, 448);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (454, 'Khu cách ly Tăng - Trương', 597, 10, 454);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (459, 'Bệnh viện Lê Inc', 4527, 3557, 459);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (464, 'Khu cách ly Dương, Phạm and Tô', 4083, 3323, 464);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (469, 'Bệnh viện Tăng - Vũ', 444, 4334, 469);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (474, 'Khu cách ly Phan - Mai', 2012, 841, 474);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (479, 'Bệnh viện Nguyễn - Trịnh', 3024, 761, 479);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (484, 'Khu cách ly Dương, Hồ and Lâm', 3797, 2456, 484);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (489, 'Bệnh viện Vũ - Trương', 2049, 723, 489);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (494, 'Khu cách ly Tăng - Tăng', 818, 3835, 494);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (499, 'Bệnh viện Trịnh, Đinh and Hoàng', 4582, 1546, 499);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (107, 'Bệnh viện Lý - Lâm', 4221, 4379, 107);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (117, 'Bệnh viện Lý, Hồ and Trương', 2508, 3106, 117);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (122, 'Khu cách ly Hồ, Tô and Đỗ', 467, 910, 122);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (128, 'Khu cách ly Đoàn Inc', 3159, 807, 128);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (133, 'Bệnh viện Lê - Hoàng', 4420, 2289, 133);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (138, 'Khu cách ly Tăng, Hà and Phạm', 1806, 3221, 138);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (143, 'Bệnh viện Đinh - Lâm', 3020, 2767, 143);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (148, 'Khu cách ly Ngô, Bùi and Đinh', 888, 1138, 148);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (153, 'Bệnh viện Đỗ and Sons', 388, 4444, 153);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (158, 'Khu cách ly Hà, Nguyễn and Trịnh', 3957, 2797, 158);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (163, 'Bệnh viện Hà - Đặng', 587, 2423, 163);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (169, 'Bệnh viện Vũ - Tăng', 3700, 2528, 169);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (174, 'Khu cách ly Đoàn, Đỗ and Hồ', 1006, 4518, 174);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (179, 'Bệnh viện Đặng, Phùng and Lâm', 1135, 2547, 179);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (184, 'Khu cách ly Mai, Hà and Phùng', 4498, 2566, 184);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (189, 'Bệnh viện Lê - Tăng', 1141, 3291, 189);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (194, 'Khu cách ly Đỗ - Hồ', 521, 4828, 194);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (199, 'Bệnh viện Hồ LLC', 3525, 2464, 199);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (204, 'Khu cách ly Phan - Đỗ', 4700, 3553, 204);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (209, 'Bệnh viện Hồ - Trương', 1661, 3651, 209);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (214, 'Khu cách ly Hồ, Lý and Tô', 1004, 4659, 214);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (220, 'Khu cách ly Tô - Hà', 190, 2159, 220);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (225, 'Bệnh viện Đinh - Hoàng', 1068, 374, 225);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (232, 'Khu cách ly Lý, Vũ and Tô', 1148, 447, 232);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (237, 'Bệnh viện Lý Group', 2962, 3853, 237);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (242, 'Khu cách ly Lâm - Trần', 3654, 2437, 242);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (247, 'Bệnh viện Phùng LLC', 1006, 3369, 247);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (252, 'Khu cách ly Đào, Trần and Đoàn', 4629, 691, 252);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (257, 'Bệnh viện Đỗ - Lâm', 2097, 3850, 257);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (262, 'Khu cách ly Trịnh - Vũ', 4513, 3348, 262);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (267, 'Bệnh viện Dương Group', 3507, 4185, 267);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (272, 'Khu cách ly Trần - Lâm', 1180, 985, 272);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (277, 'Bệnh viện Đoàn, Trần and Đỗ', 2399, 4231, 277);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (283, 'Bệnh viện Đào, Ngô and Mai', 810, 3450, 283);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (288, 'Khu cách ly Đào, Đặng and Mai', 3971, 744, 288);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (293, 'Bệnh viện Nguyễn, Đỗ and Vũ', 1346, 1440, 293);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (298, 'Khu cách ly Tô, Vũ and Hồ', 3933, 4939, 298);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (303, 'Bệnh viện Tô, Lê and Đinh', 376, 13, 303);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (308, 'Khu cách ly Lý Group', 4199, 2660, 308);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (313, 'Bệnh viện Hồ, Phùng and Phạm', 4235, 2510, 313);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (318, 'Khu cách ly Đào LLC', 2127, 4396, 318);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (323, 'Bệnh viện Phan - Tô', 2429, 2436, 323);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (328, 'Khu cách ly Vương, Hồ and Tăng', 4180, 1589, 328);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (333, 'Bệnh viện Lâm, Dương and Nguyễn', 1804, 850, 333);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (338, 'Khu cách ly Vũ, Tô and Nguyễn', 637, 1131, 338);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (343, 'Bệnh viện Hà, Tăng and Tô', 695, 3742, 343);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (348, 'Khu cách ly Phùng - Hồ', 1846, 4327, 348);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (353, 'Bệnh viện Đào, Hồ and Vũ', 1491, 317, 353);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (358, 'Khu cách ly Tô - Đoàn', 301, 4318, 358);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (363, 'Bệnh viện Dương and Sons', 1484, 1672, 363);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (368, 'Khu cách ly Trương, Đào and Tăng', 2411, 150, 368);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (373, 'Bệnh viện Trịnh, Vũ and Vũ', 4016, 3581, 373);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (378, 'Khu cách ly Tăng Group', 1401, 4599, 378);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (383, 'Bệnh viện Trịnh and Sons', 3514, 1954, 383);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (388, 'Khu cách ly Trương - Lê', 4723, 479, 388);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (393, 'Bệnh viện Đào - Lý', 1634, 2160, 393);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (398, 'Khu cách ly Mai and Sons', 4113, 2307, 398);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (403, 'Bệnh viện Lê and Sons', 908, 4960, 403);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (409, 'Bệnh viện Nguyễn LLC', 4817, 3953, 409);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (414, 'Khu cách ly Đoàn and Sons', 4415, 1623, 414);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (419, 'Bệnh viện Hồ, Phạm and Đỗ', 4156, 3510, 419);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (424, 'Khu cách ly Đào LLC', 4278, 3224, 424);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (429, 'Bệnh viện Phùng - Bùi', 2707, 1381, 429);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (434, 'Khu cách ly Đỗ, Lâm and Phan', 3138, 4007, 434);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (439, 'Bệnh viện Đào LLC', 3198, 2071, 439);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (444, 'Khu cách ly Đặng - Dương', 3519, 1449, 444);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (449, 'Bệnh viện Lý LLC', 3675, 3201, 449);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (453, 'Bệnh viện Hồ, Trịnh and Đào', 626, 4137, 453);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (458, 'Khu cách ly Bùi, Dương and Hà', 4814, 4064, 458);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (463, 'Bệnh viện Phan, Đinh and Lê', 4594, 1418, 463);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (468, 'Khu cách ly Tăng - Lâm', 1943, 3298, 468);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (473, 'Bệnh viện Hồ, Đỗ and Lê', 3942, 2263, 473);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (478, 'Khu cách ly Tô LLC', 1666, 4813, 478);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (483, 'Bệnh viện Lê LLC', 4189, 2287, 483);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (488, 'Khu cách ly Tô, Đào and Hà', 1035, 4934, 488);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (493, 'Bệnh viện Đào - Đinh', 3242, 579, 493);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (498, 'Khu cách ly Phùng - Phạm', 1642, 3129, 498);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (361, 'Bệnh viện Trương - Tăng', 1625, 728, 361);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (366, 'Khu cách ly Vương, Đoàn and Bùi', 2812, 2889, 366);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (370, 'Khu cách ly Trương - Đinh', 2198, 4201, 370);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (375, 'Bệnh viện Trương and Sons', 403, 4353, 375);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (380, 'Khu cách ly Trương, Hồ and Đào', 4700, 3999, 380);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (385, 'Bệnh viện Hoàng, Lê and Đoàn', 3467, 2981, 385);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (390, 'Khu cách ly Tô Group', 1864, 691, 390);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (395, 'Bệnh viện Đào Group', 3017, 2050, 395);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (400, 'Khu cách ly Ngô, Ngô and Bùi', 1244, 1134, 400);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (405, 'Bệnh viện Trịnh - Hà', 723, 3800, 405);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (410, 'Khu cách ly Đào, Tô and Hồ', 2228, 1140, 410);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (415, 'Bệnh viện Lê - Tô', 2837, 982, 415);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (420, 'Khu cách ly Bùi - Phạm', 4842, 4375, 420);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (425, 'Bệnh viện Nguyễn Group', 2683, 222, 425);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (430, 'Khu cách ly Ngô, Đào and Phùng', 2447, 3645, 430);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (435, 'Bệnh viện Dương, Đặng and Phạm', 4119, 2999, 435);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (440, 'Khu cách ly Mai, Ngô and Bùi', 1885, 2678, 440);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (445, 'Bệnh viện Hoàng Group', 136, 2267, 445);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (450, 'Khu cách ly Hồ Inc', 1290, 1680, 450);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (455, 'Bệnh viện Trần - Lâm', 3015, 2962, 455);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (460, 'Khu cách ly Đặng, Vương and Lê', 1984, 4696, 460);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (465, 'Bệnh viện Tô - Vũ', 3025, 3567, 465);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (470, 'Khu cách ly Phan, Đoàn and Trương', 2600, 346, 470);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (475, 'Bệnh viện Đào - Hà', 3266, 1608, 475);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (480, 'Khu cách ly Đào - Hồ', 1091, 3683, 480);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (485, 'Bệnh viện Hoàng - Tăng', 1456, 3766, 485);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (490, 'Khu cách ly Lý - Trương', 1469, 862, 490);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (495, 'Bệnh viện Lý, Lâm and Đào', 2496, 4611, 495);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (365, 'Bệnh viện Nguyễn LLC', 1330, 3200, 365);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (371, 'Bệnh viện Phùng, Phùng and Lê', 2327, 2608, 371);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (376, 'Khu cách ly Dương Inc', 2089, 3786, 376);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (381, 'Bệnh viện Phạm - Bùi', 1819, 2546, 381);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (386, 'Khu cách ly Đinh, Phan and Đoàn', 514, 2486, 386);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (391, 'Bệnh viện Lâm - Phùng', 1511, 2347, 391);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (396, 'Khu cách ly Dương, Phan and Phùng', 2095, 2062, 396);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (401, 'Bệnh viện Đào Inc', 4070, 306, 401);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (407, 'Bệnh viện Phùng - Đào', 3463, 571, 407);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (412, 'Khu cách ly Ngô - Bùi', 4854, 638, 412);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (417, 'Bệnh viện Trương - Vương', 1814, 299, 417);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (422, 'Khu cách ly Đinh LLC', 2597, 2808, 422);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (427, 'Bệnh viện Trương - Lâm', 1625, 746, 427);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (432, 'Khu cách ly Tô, Dương and Đào', 3552, 1101, 432);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (437, 'Bệnh viện Lý LLC', 2055, 3215, 437);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (442, 'Khu cách ly Đỗ and Sons', 2399, 3823, 442);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (447, 'Bệnh viện Phùng - Trần', 1636, 3929, 447);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (452, 'Khu cách ly Trương and Sons', 4107, 1924, 452);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (457, 'Bệnh viện Lâm - Bùi', 1352, 2736, 457);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (462, 'Khu cách ly Hà Group', 395, 253, 462);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (467, 'Bệnh viện Lê - Trịnh', 2797, 1896, 467);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (472, 'Khu cách ly Hoàng, Mai and Hà', 1689, 1279, 472);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (477, 'Bệnh viện Lê LLC', 2607, 2078, 477);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (482, 'Khu cách ly Đỗ LLC', 3144, 558, 482);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (487, 'Bệnh viện Đào Inc', 1038, 4244, 487);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (492, 'Khu cách ly Ngô Group', 2694, 572, 492);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (497, 'Bệnh viện Đào - Tô', 700, 2820, 497);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (105, 'Bệnh viện Đào, Trương and Ngô', 3314, 4832, 105);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (116, 'Khu cách ly Đặng - Trương', 480, 2485, 116);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (121, 'Bệnh viện Ngô Inc', 4601, 4584, 121);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (127, 'Bệnh viện Tô, Đặng and Lê', 958, 3096, 127);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (132, 'Khu cách ly Vương - Lý', 633, 3544, 132);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (137, 'Bệnh viện Phạm LLC', 315, 3921, 137);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (142, 'Khu cách ly Hoàng, Hoàng and Ngô', 2747, 4933, 142);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (147, 'Bệnh viện Vương, Vũ and Mai', 1753, 4809, 147);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (152, 'Khu cách ly Bùi - Trần', 4408, 766, 152);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (157, 'Bệnh viện Dương - Trần', 2800, 2680, 157);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (162, 'Khu cách ly Bùi, Vũ and Hồ', 2993, 2112, 162);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (168, 'Khu cách ly Vũ - Phan', 4462, 1768, 168);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (173, 'Bệnh viện Ngô Group', 2217, 3193, 173);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (178, 'Khu cách ly Hồ, Trương and Đặng', 403, 3877, 178);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (183, 'Bệnh viện Hà, Phạm and Vũ', 1908, 338, 183);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (188, 'Khu cách ly Vũ, Lê and Bùi', 1398, 3140, 188);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (193, 'Bệnh viện Phạm - Vương', 2355, 3302, 193);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (198, 'Khu cách ly Trương - Đặng', 4649, 3848, 198);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (203, 'Bệnh viện Bùi - Hồ', 661, 1371, 203);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (208, 'Khu cách ly Trương LLC', 1191, 99, 208);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (213, 'Bệnh viện Nguyễn, Trương and Phùng', 2386, 2762, 213);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (219, 'Bệnh viện Đặng, Dương and Vương', 3147, 1306, 219);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (224, 'Khu cách ly Trần, Phùng and Phạm', 2225, 1394, 224);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (226, 'Khu cách ly Phùng, Vũ and Lê', 314, 1143, 226);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (230, 'Khu cách ly Lâm, Tô and Phạm', 2962, 1026, 230);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (235, 'Bệnh viện Lê, Vương and Đoàn', 335, 3351, 235);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (240, 'Khu cách ly Bùi - Lê', 4840, 1371, 240);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (245, 'Bệnh viện Dương - Trịnh', 1839, 2040, 245);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (250, 'Khu cách ly Hà and Sons', 2261, 799, 250);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (256, 'Khu cách ly Bùi Group', 1935, 1333, 256);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (261, 'Bệnh viện Đinh and Sons', 1292, 3193, 261);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (266, 'Khu cách ly Phùng Inc', 3902, 3425, 266);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (271, 'Bệnh viện Vũ, Bùi and Đinh', 2923, 4782, 271);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (276, 'Khu cách ly Mai - Đặng', 1983, 392, 276);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (281, 'Bệnh viện Đào Inc', 4693, 4532, 281);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (287, 'Bệnh viện Trịnh and Sons', 608, 2129, 287);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (292, 'Khu cách ly Dương, Vũ and Đỗ', 1059, 3837, 292);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (294, 'Khu cách ly Bùi, Vương and Tăng', 965, 2323, 294);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (299, 'Bệnh viện Hoàng Inc', 122, 2247, 299);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (304, 'Khu cách ly Ngô LLC', 3089, 409, 304);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (309, 'Bệnh viện Đỗ Group', 3903, 3051, 309);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (314, 'Khu cách ly Vương - Nguyễn', 346, 1491, 314);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (319, 'Bệnh viện Vũ, Đặng and Đinh', 2427, 1531, 319);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (324, 'Khu cách ly Phùng, Hồ and Tô', 2068, 106, 324);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (329, 'Bệnh viện Ngô and Sons', 3000, 1190, 329);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (334, 'Khu cách ly Trần Group', 598, 1794, 334);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (339, 'Bệnh viện Đỗ, Phạm and Mai', 4191, 1044, 339);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (344, 'Khu cách ly Bùi - Tô', 1273, 2477, 344);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (349, 'Bệnh viện Lâm Inc', 1381, 2694, 349);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (354, 'Khu cách ly Ngô - Mai', 1131, 1400, 354);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (359, 'Bệnh viện Trương - Tăng', 4078, 2868, 359);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (364, 'Khu cách ly Đỗ and Sons', 3470, 2883, 364);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (369, 'Bệnh viện Phùng, Phùng and Nguyễn', 1171, 2516, 369);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (374, 'Khu cách ly Đoàn Inc', 2663, 1806, 374);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (379, 'Bệnh viện Đặng - Bùi', 400, 2924, 379);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (384, 'Khu cách ly Lê and Sons', 3491, 2423, 384);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (389, 'Bệnh viện Mai Group', 2609, 2345, 389);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (394, 'Khu cách ly Hà - Hà', 2099, 1673, 394);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (399, 'Bệnh viện Đào, Lâm and Dương', 2992, 648, 399);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (404, 'Khu cách ly Phùng, Vương and Vương', 1553, 1312, 404);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (406, 'Khu cách ly Dương, Nguyễn and Đỗ', 3909, 1120, 406);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (411, 'Bệnh viện Hồ - Đào', 694, 2732, 411);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (416, 'Khu cách ly Vương - Lý', 1037, 4807, 416);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (421, 'Bệnh viện Trịnh, Vương and Đinh', 3271, 2380, 421);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (426, 'Khu cách ly Lý - Đặng', 2584, 242, 426);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (431, 'Bệnh viện Đinh - Tô', 2270, 316, 431);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (436, 'Khu cách ly Phạm, Lâm and Đào', 421, 2616, 436);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (441, 'Bệnh viện Hoàng, Lê and Vương', 2638, 3768, 441);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (446, 'Khu cách ly Lý, Trần and Đặng', 2998, 4943, 446);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (451, 'Bệnh viện Dương LLC', 4605, 3273, 451);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (456, 'Khu cách ly Tăng LLC', 3120, 1898, 456);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (461, 'Bệnh viện Đỗ LLC', 2024, 2176, 461);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (466, 'Khu cách ly Bùi - Vương', 121, 986, 466);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (471, 'Bệnh viện Tô LLC', 3738, 268, 471);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (476, 'Khu cách ly Hoàng - Trịnh', 3127, 2190, 476);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (481, 'Bệnh viện Hoàng LLC', 1427, 535, 481);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (486, 'Khu cách ly Đào and Sons', 4195, 2633, 486);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (491, 'Bệnh viện Đoàn, Phạm and Lê', 1694, 4046, 491);
INSERT INTO "IsolationFacility"("isolationFacilityId", "isolationFacilityName", "capacity", "currentQuantity", "addressId") VALUES (496, 'Khu cách ly Vũ - Trịnh', 2968, 2444, 496);
